### ISSUE TITLE
Add selective wrapping arithmetic

### ISSUE THREAD

**Issue by PTaylor-FluenTech** [PTaylor-FluenTech/embedded-time#5]
Wrapping arithmetic is needed where a counter may roll over at some point. Using wrapping arithmetic, allows for the full width of the counter to be considered regardless of the current count value.

# Looking at the [RTFM](https://github.com/rtfm-rs/cortex-m-rtfm/blob/master/src/cyccnt.rs) CYCCNT implementation as a reference
- Instance is a i32
- Duration is a u32

Wrapping arithmetic is used when finding the difference of two instances. This is a signed `wrapping_sub` and panics if the result is negative (in the expression `I1-I2`, `I1` must be a "later" instance than `I2`. _In what situations could the `wrapping_sub` mis-interpret the ordering of the instances?_ 

When adding or subtracting a duration from an instance, the duration (stored as a `u32`) must be less than `i32::MAX` and is interpreted as an `i32` for the wrapping arithmetic. _So why is it stored as a `u32` in the first place? (#7)_

Wrapping arithmetic is only used when working with instances. This is because it is the instances that are derived from some counter(s) that might wrap around.

**Comment by tib888** [comment]
saturating add/sub can be also useful for durations, to avoid overflow when summing up many small duration in a accumulator...

**Comment by PTaylor-FluenTech** [comment]
@tib888 Thank you for the recommendation. I will definitely take a look at that.
